### ISSUE TITLE
Unable to get Landlord tenant to work. 

### ISSUE THREAD

**Issue by captdeys** [torzer/awesome-landlord#16]
Hi, 

I have followed your instructions but this package isnt injecting the where "company_id = X" into the SQL queries. 

1. Added the Landlord Service Provider in the config/app.php
2. Added the alias in the config/app.php
3. Created config file and set the tenant_id to company_id
4. Created and set the landlord middleware and I know that works
5. Added BelongsToTenants scope to the user model

When all call $usersList = User::all('name', 'email','phone_number','profile_url'); in the userController, the company_id is not injected in the sql. I even had \Landlord::enable() called before that to make sure it is on. 

What do you think I could be doing wrong?

Thanks

**Comment by nunomazer** [comment]
Hi, 

some checks:
- do your users records have the company_id field and are filled with the correct id ?
- are you sure the middleware is being called at request chain? you can do a `dd` in the handle function to check

**Comment by captdeys** [comment]
Hi,

- Yes, the users table has a company_id field and all are correctly filled. It reference a column on another table to, so it isnt allowed to be empty.

- Yes, my middleware is being called. dd in the handle kills the request and show the text I placed in the function. 

I am wondering if there is some Laravel compatibility issue I am over looking.

**Comment by nunomazer** [comment]
Well, it seems everything is ok based on your descriptions, may you give me access to a repository so I could  try to help you to find the problem?

**Comment by dmarcos89** [comment]
Hey, i am facing this exact problem. I used the package before and worked perfectyl, but now it doesn't seem to be working on Laravel 7..

@adnansyedimadi how did you solve this?

Thanks

**Comment by arislanhaikal** [comment]
I have some issue. This is not working if scope in controller. 
But if I call model with BelongsToTenants in route its working well.  
I use Laravel 8, PHP 8.

**Comment by captdeys** [comment]
No. I never really got it working. I ended just manually adding the scopes to my SQL calls. 

@nunomazer I just saw this your comment. Sorry. I might have missed it. I can't give you access due to company's proprietary work. I will likely DM you if I need help with this package again. Right now, trying to get this package to work been shelved, as manually doing is working well for my needs for now.

**Comment by nunomazer** [comment]
@adnansyedimadi can you share pieces of the code here ? Only the necessary to understand where did ou tried to scope the tenant that didn't work

**Comment by nunomazer** [comment]
@arislanhaikal could you please open a new issue with your problem? I'm closing this since @adnansyedimadi said it has the problem solved by another strategy.
