### ISSUE TITLE
Tenant is adding on midlleware buts on traist is null

### ISSUE THREAD

**Issue by iurylippo** [torzer/awesome-landlord#18]
```
public function handle($request, Closure $next)
    {

        if (auth()->check()) {
            if (auth()->user()->tenant_id) {
                Landlord::addTenant('tenant_id', \auth()->user()->tenant_id);
            }
        }
        dd(Landlord::getTenants());
        return $next($request);
    }
```
dump:
Illuminate\Support\Collection {#1315 ▼
  #items: array:1 [▼
    "tenant_id" => 2
  ]
}

```
public static function bootBelongsToTenants()
    {

        // Grab our singleton from the container
        static::$landlord = app(TenantManager::class);

        // Add a global scope for each tenant this model should be scoped by.
        static::$landlord->applyTenantScopes(new static());
        dd(static::$landlord);

        // Add tenantColumns automatically when creating models
        static::creating(function (Model $model) {
            static::$landlord->newModel($model);
        });

    }
```
dump:
Torzer\Awesome\Landlord\TenantManager {#1314 ▼
  #enabled: true
  #tenants: Illuminate\Support\Collection {#1315 ▼
    #items: []
  }
  #deferredModels: Illuminate\Support\Collection {#1316 ▼
    #items: array:1 [▼
      0 => Modules\System\Entities\Usergroup {#1317 ▶}
    ]
  }
}

But when I put the content of middleware on applyTenantScopes function it works and my request is filtered by tenant_id perfectly:

```
public function applyTenantScopes(Model $model)
    {

        if (!$this->enabled) {
            return;
        }

        if (auth()->check()) {
            if (auth()->user()->tenant_id) {
                $this->addTenant(auth()->user()->tenant, \auth()->user()->tenant_id);
            }
        }
....
```
I wanna understand what I'm doing wrong, please

**Comment by iurylippo** [comment]
Solved! inside scope middleware I put Landlord::applyTenantScopesToDeferredModels(); after add the Tenant, It's something with booting order on laravel, this function was created to solved that.

Please, put that on readme, the original repo also does not mention it, I found scouring some old issues there.

**Comment by nunomazer** [comment]
Thanks @iurylippo .. gonna add it to doc
