### ISSUE TITLE
Help with Laravel 5.7

### ISSUE THREAD

**Issue by diegonella** [torzer/awesome-landlord#3]
I'm using next code
`Landlord :: addTenant ('schema_id', 3);`
`$ac = \App\Accounts::all();`

Return
`{`
`id: 1`
`schema_id: 1,`
`name: 'Demo 1'`
`},`
`{`
`id: 2,`
`schema_id: 2,`
`name: 'Demo 2'`
`}`

what am I doing wrong?

**Comment by nunomazer** [comment]
Does your model use the trait BelongsToTenants?

```
use Illuminate\Database\Eloquent\Model;
use Torzer\Awesome\Landlord\BelongsToTenants;

class ExampleModel extends Model
{
    use BelongsToTenants;
    
    public $tenantColumns = ['tenant_id'];
}
```

**Comment by diegonella** [comment]
Yes, my problem is i have use a Model that extend BaseModel that extend Model, and another namespace.
If a try on \App\MyModel, run perfect, but not from
\CustomModules\MyModule\Models\MyModel

And i not found the error

**Comment by nunomazer** [comment]
This should not be a problem, using a custom namespace that is not App.

Could you attach an example so I can test it?
