### ISSUE TITLE
Call to a member function newQueryWithoutTenants() on null

### ISSUE THREAD

**Issue by aronduby** [torzer/awesome-landlord#9]
I'm in the middle of upgrading PHP to 7.3.9, Laravel to 5.6, and my app so I am migrating to your fork (which thank you by the way). But part of my code is trying to do a query without the tenants and it's failing.

```php
// in DataProvider class
    protected function getPhotoQuery()
    {
        return Photo::allTenants() // <---- error here
            ->select('photos.*')
            ->join('photo_player', 'photos.id', '=', 'photo_player.photo_id')
            ->where('photo_player.season_id', '=', $this->playerSeason->season_id)
            ->where('photo_player.player_id', '=', $this->player->id)
            ->orderBy('photos.created_at', 'desc');
    }
```

```
Symfony\Component\Debug\Exception\FatalThrowableError thrown with message "Call to a member function newQueryWithoutTenants() on null"

Stacktrace:
#1 Symfony\Component\Debug\Exception\FatalThrowableError in PATH\vendor\torzer\awesome-landlord\src\BelongsToTenants.php:69
```

Here's the entirety of my Photo class

```php
<?php

namespace App\Models;

use Torzer\Awesome\Landlord\BelongsToTenants AS BelongsToTenant;
use Illuminate\Database\Eloquent\Model;

class Photo extends Model
{
    use BelongsToTenant;

    public function getPhotoAttribute()
    {
        return config('urls.photos') . '/' . $this->file . '.jpg';
    }

    public function getThumbAttribute()
    {
        return config('urls.photos') . '/thumbs/' . $this->file . '.jpg';
    }

    public function getJSONData(Player $player = null)
    {
        $json = ['main'=>null, 'also'=>[]];
        $playersTemp = $this->players;

        if($player != null){
            $playersTemp = $playersTemp->reject(function($p) use($player) {
                return $p->id === $player->id;
            });

            $json['main'] = $player->toArray();
        }

        if($playersTemp->count()){
            $json['also'] = $playersTemp->toArray();
        }

        return json_encode($json);
    }

    public function albums()
    {
        return $this->belongsToMany('App\Models\PhotoAlbum', 'album_photo');
    }

    public function players()
    {
        return $this->belongsToMany('App\Models\Player');
    }
}
```

**Comment by nunomazer** [comment]
Hi @aronduby,

it seams, for some reason, that the TenantClass is not instantiated in BelongsToTenants  boot.

See the code forward:

    public static function bootBelongsToTenants()
        {
            // Grab our singleton from the container
            static::$landlord = app(TenantManager::class);


A possibility is that LandlordServiceProvider hasn't executed yet at this point of your code.

Are you trying to run this qury in a middleware or in another Service Provider?

**Comment by aronduby** [comment]
@nunomazer nope, running within a http controller method.  ~Debug breakpoint right after that line shows that variable is set:~

[image deleted, ended up breakpoint was done wrong and not relevant]

**Comment by nunomazer** [comment]
Is your code open source? Can you send here the address than I can perform local tests?

**Comment by aronduby** [comment]
I don't have the current version with your package subbed in up yet, will try to get it up tonight, but the current code running old version of hipsterjazzbo's code is at https://github.com/aronduby/hwp if you want to look at that. That query happens in the App\Services\PlayerData\Providers\SeasonProvider.php

**Comment by aronduby** [comment]
Currently ignoring some other stuff and digging through old issues and PRs and it looks like this one is likely to be the cause/fix, will try it myself once I get back to full code https://github.com/hipsterjazzbo/Landlord/pull/75

**Comment by aronduby** [comment]
back now and confirmed the code from that PR fixes it

**Comment by nunomazer** [comment]
Thanks for find the problem and point me the solution, I have just implemented it. Can you try it updating the package version to 3.1.0? 

I gonna close this issue, if the problem persist please reopen it.

**Comment by aronduby** [comment]
working great, thanks!
